import datetime
from typing import Any, Callable, Iterable, Iterator, Literal, Mapping, Sequence, overload

from ._globals import DEFAULT
from .base import DAL
from .helpers.classes import (
    BasicStorage,
    MethodAdder,
    OpRow,
    Reference,
    Serializable,
    SQLALL,
    SQLCallableList,
    SQLCustomType,
)

_Types = str | SQLCustomType | type[Any]
_Limitby = tuple[int, int]
_Orderby = Any

class Row(BasicStorage):
    """A single record. Columns are reachable as attributes and as items."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, k: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getattr__(self, k: str) -> Any: ...
    def __contains__(self, k: Any) -> bool: ...
    def __int__(self) -> int: ...
    def __long__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __call__(self, k: Any) -> Any: ...
    def __copy__(self) -> Row: ...
    def __eq__(self, other: object) -> bool: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def as_dict(
        self,
        datetime_to_str: bool = ...,
        custom_types: type[Any] | Iterable[type[Any]] | None = ...,
    ) -> dict[str, Any]: ...
    def as_xml(
        self, row_name: str = ..., colnames: Sequence[str] | None = ..., indent: str = ...
    ) -> str: ...
    def as_json(
        self,
        mode: str = ...,
        default: Callable[[Any], Any] | None = ...,
        colnames: Sequence[str] | None = ...,
        serialize: bool = ...,
        **kwargs: Any,
    ) -> Any: ...

def pickle_row(s: Row) -> tuple[Any, ...]: ...

class Table(Serializable, BasicStorage):
    """
    A defined table. Unknown attributes resolve to the table's `Field`s, which is
    how `db.person.name` works at runtime.
    """

    _db: DAL
    _tablename: str
    _actual_tablename: str
    _rname: str
    _raw_rname: str
    _sequence_name: str
    _trigger_name: str
    _common_filter: Callable[..., Any] | None
    _format: str | Callable[[Row], str] | None
    _singular: str
    _plural: str
    _primarykey: list[str]
    _fields: SQLCallableList
    _id: Field
    _before_insert: list[Callable[[OpRow], Any]]
    _after_insert: list[Callable[[OpRow, Any], Any]]
    _before_update: list[Callable[[Set, OpRow], Any]]
    _after_update: list[Callable[[Set, OpRow], Any]]
    _before_delete: list[Callable[[Set], Any]]
    _after_delete: list[Callable[[Set], Any]]
    ALL: SQLALL
    virtualfields: list[Any]
    add_method: MethodAdder
    _actual: bool
    _dalname: str
    _migrate: bool | str | None
    _references: list[Field]
    _referenced_by: list[Field]
    _referenced_by_list: list[Field]
    _virtual_fields: list[Any]
    _virtual_methods: list[Any]

    def __init__(
        self, db: DAL, tablename: str, *fields: Field | Table | str, **args: Any
    ) -> None: ...
    @property
    def fields(self) -> SQLCallableList: ...
    # Unknown attributes are the table's columns; see also `__getitem__`.
    def __getattr__(self, key: str) -> Field: ...
    @overload
    def __getitem__(self, key: str) -> Field: ...
    @overload
    def __getitem__(self, key: int) -> Row | None: ...
    @overload
    def __getitem__(self, key: Mapping[str, Any]) -> Row | None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __call__(self, key: Any = ..., **kwargs: Any) -> Row | None: ...
    # pyDAL iterates a table's fields, not the mapping keys `BasicStorage` yields.
    def __iter__(self) -> Iterator[Field]: ...  # type: ignore[override]
    def __str__(self) -> str: ...
    @property
    def sqlsafe(self) -> str: ...
    @property
    def sqlsafe_alias(self) -> str: ...
    @property
    def sql_shortref(self) -> str: ...
    @property
    def sql_fullref(self) -> str: ...
    @property
    def _structure(self) -> Any: ...
    def _filter_fields_for_operation(self, fields: Any) -> list[tuple[Field, Any]]: ...
    def _compute_fields_for_operation(
        self, fields: Any, to_compute: Any
    ) -> OpRow: ...
    def _fields_and_values_for_insert(self, fields: Any) -> OpRow: ...
    def _fields_and_values_for_update(self, fields: Any) -> OpRow: ...
    def query_name(self, *args: Any, **kwargs: Any) -> tuple[str, ...]: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def _drop(self, mode: str = ...) -> str: ...
    def drop(self, mode: str = ...) -> None: ...
    def _truncate(self, mode: str = ...) -> str: ...
    def _insert(self, **fields: Any) -> str: ...
    def _validate(self, **vars: Any) -> dict[str, Any]: ...
    def _build_query(self, key: Mapping[str, Any]) -> Query | None: ...
    def _filter_fields(
        self, record: Any, allow_id: bool = ..., writable_only: bool = ...
    ) -> dict[str, Any]: ...
    # `record` is duck-typed: pyDAL only ever calls `record.get("id")` on it, so
    # ORM row wrappers are legitimate here.
    def _validate_fields(
        self, fields: Mapping[str, Any], record: Any = ...
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
    def _create_references(self) -> None: ...
    def _enable_record_versioning(
        self,
        archive_db: DAL | None = ...,
        archive_name: str = ...,
        is_active: str = ...,
        current_record: str = ...,
        current_record_label: str | None = ...,
        migrate: Any = ...,
        redefine: Any = ...,
    ) -> None: ...
    def _upload_fieldnames(self) -> set[str]: ...
    def truncate(self, mode: str = ...) -> None: ...
    # Returns the new row id. pyDAL hands back a `Reference` bound to this table,
    # except when a `_before_insert` callback aborts the insert and `0` is returned.
    def insert(self, **fields: Any) -> Reference: ...
    def bulk_insert(self, items: Iterable[Mapping[str, Any]]) -> list[Reference]: ...
    def validate_and_insert(self, **fields: Any) -> dict[str, Any]: ...
    def validate_and_update(self, _key: Any, **fields: Any) -> dict[str, Any]: ...
    def update_or_insert(self, _key: Any = ..., **values: Any) -> Reference | None: ...
    def validate_and_update_or_insert(
        self, _key: Any = ..., **fields: Any
    ) -> dict[str, Any]: ...
    def import_from_csv_file(
        self,
        csvfile: Any,
        id_map: Mapping[str, Any] | None = ...,
        null: str = ...,
        unique: str = ...,
        id_offset: Mapping[str, Any] | None = ...,
        transform: Callable[[Any], Any] | None = ...,
        validate: bool = ...,
        encoding: str = ...,
        **kwargs: Any,
    ) -> Any: ...
    def as_dict(self, flat: bool = ..., sanitize: bool = ...) -> dict[str, Any]: ...
    def with_alias(self, alias: str) -> Table: ...
    def on(self, query: Query | Expression | bool) -> Expression: ...
    def create_index(self, name: str, *fields: Field | str, **kwargs: Any) -> Any: ...
    def drop_index(self, name: str, if_exists: bool = ...) -> Any: ...

class Select(BasicStorage):
    """A nested/CTE select usable in place of a table."""

    ALL: SQLALL
    _db: DAL
    _tablename: str
    _rname: str
    _raw_rname: str
    _query: Query | None
    _qfields: list[Any]
    _fields: list[str]
    _attributes: dict[str, Any]
    _common_filter: Any
    _correlated: bool
    _cte_recursive: bool
    _virtual_fields: list[Any]
    _virtual_methods: list[Any]
    _sql_cache: Any
    _colnames_cache: Any
    virtualfields: list[Any]

    def __init__(
        self, db: DAL, query: Query | None, fields: Sequence[Any], attributes: Mapping[str, Any]
    ) -> None: ...
    @property
    def fields(self) -> list[str]: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Field: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __call__(self) -> Rows: ...
    # As with `Table`, iteration yields fields rather than mapping keys.
    def __iter__(self) -> Iterator[Field]: ...  # type: ignore[override]
    def __str__(self) -> str: ...
    def with_alias(self, alias: str) -> Select: ...
    def on(self, query: Query | Expression | bool) -> Expression: ...
    def union(self, recursive: Any, union_type: str = ...) -> Select: ...
    def union_all(self, recursive: Any) -> Select: ...
    def cte(self, cte_collector: Any) -> Any: ...
    def query_name(self, outer_scoped: list[Any] = ...) -> tuple[str, ...]: ...
    @property
    def sql_shortref(self) -> str: ...
    @property
    def is_cte(self) -> bool: ...
    def wrap(self, *args: Any, **kwargs: Any) -> Select: ...
    def _compile(
        self,
        outer_scoped: list[Any] = ...,
        with_alias: bool = ...,
        cte_collector: Any = ...,
    ) -> tuple[Any, ...]: ...
    def _filter_fields(self, record: Any, id: bool = ...) -> dict[str, Any]: ...

class Expression:
    """A SQL expression. Comparisons build `Query` objects rather than booleans."""

    _dialect_expressions_: dict[str, Any]
    db: DAL
    op: Any
    first: Any
    second: Any
    type: Any
    tablename: str | None
    _table: Table | None
    _itype: str | None
    optional_args: dict[str, Any]

    @property
    def _dialect(self) -> Any: ...
    def __init__(
        self,
        db: DAL,
        op: Any,
        first: Any = ...,
        second: Any = ...,
        type: Any = ...,
        tablename: str | None = ...,
        **optional_args: Any,
    ) -> None: ...
    def sum(self) -> Expression: ...
    def max(self) -> Expression: ...
    def min(self) -> Expression: ...
    def len(self) -> Expression: ...
    def avg(self) -> Expression: ...
    def abs(self) -> Expression: ...
    def cast(self, cast_as: Any, **kwargs: Any) -> Expression: ...
    def lower(self) -> Expression: ...
    def upper(self) -> Expression: ...
    def replace(self, a: Any, b: Any) -> Expression: ...
    def year(self) -> Expression: ...
    def month(self) -> Expression: ...
    def day(self) -> Expression: ...
    def hour(self) -> Expression: ...
    def minutes(self) -> Expression: ...
    def seconds(self) -> Expression: ...
    def epoch(self) -> Expression: ...
    def coalesce(self, *others: Any) -> Expression: ...
    def coalesce_zero(self) -> Expression: ...
    def __getitem__(self, i: int | slice) -> Expression: ...
    def __or__(self, other: Any) -> Expression: ...
    def __invert__(self) -> Expression: ...
    def __add__(self, other: Any) -> Expression: ...
    def __radd__(self, other: Any) -> Expression: ...
    def __sub__(self, other: Any) -> Expression: ...
    def __mul__(self, other: Any) -> Expression: ...
    def __div__(self, other: Any) -> Expression: ...
    def __truediv__(self, other: Any) -> Expression: ...
    def __mod__(self, other: Any) -> Expression: ...
    # Comparison operators are overloaded to build queries; this deliberately
    # departs from `object.__eq__`, matching pyDAL's runtime behavior.
    def __eq__(self, value: Any) -> Query: ...  # type: ignore[override]
    def __ne__(self, value: Any) -> Query: ...  # type: ignore[override]
    def __lt__(self, value: Any) -> Query: ...
    def __le__(self, value: Any) -> Query: ...
    def __gt__(self, value: Any) -> Query: ...
    def __ge__(self, value: Any) -> Query: ...
    def __hash__(self) -> int: ...
    def like(self, value: Any, case_sensitive: bool = ..., escape: str | None = ...) -> Query: ...
    def ilike(self, value: Any, escape: str | None = ...) -> Query: ...
    def regexp(self, value: Any, match_parameter: Any = ...) -> Query: ...
    def belongs(self, *value: Any, **kwattr: Any) -> Query: ...
    def startswith(self, value: Any) -> Query: ...
    def endswith(self, value: Any) -> Query: ...
    def contains(self, value: Any, all: bool = ..., case_sensitive: bool = ...) -> Query: ...
    def with_alias(self, alias: str) -> Expression: ...
    def st_asgeojson(self, precision: int = ..., options: int = ...) -> Expression: ...
    def st_astext(self) -> Expression: ...
    def st_aswkb(self) -> Expression: ...
    def st_x(self) -> Expression: ...
    def st_y(self) -> Expression: ...
    def st_distance(self, other: Any) -> Expression: ...
    def st_simplify(self, value: Any) -> Expression: ...
    def st_simplifypreservetopology(self, value: Any) -> Expression: ...
    def st_transform(self, value: Any) -> Expression: ...
    def st_contains(self, value: Any) -> Query: ...
    def st_equals(self, value: Any) -> Query: ...
    def st_intersects(self, value: Any) -> Query: ...
    def st_overlaps(self, value: Any) -> Query: ...
    def st_touches(self, value: Any) -> Query: ...
    def st_within(self, value: Any) -> Query: ...
    def st_dwithin(self, value: Any, distance: Any) -> Query: ...
    def json_key(self, key: str) -> Expression: ...
    def json_key_value(self, key: str) -> Expression: ...
    def json_path(self, path: str) -> Expression: ...
    def json_path_value(self, path: str) -> Expression: ...
    def json_contains(self, jsonvalue: Any) -> Query: ...

class FieldVirtual:
    name: str
    f: Callable[[Row], Any]
    type: Any
    type_name: str
    label: str
    represent: Any
    formatter: Callable[[Any], Any]
    comment: str | None
    readable: bool
    listable: bool
    searchable: bool
    writable: bool
    requires: Any
    widget: Any
    tablename: str | None
    filter_out: Callable[[Any], Any] | None
    def __init__(
        self,
        name: str | Callable[[Row], Any],
        f: Callable[[Row], Any] | None = ...,
        ftype: Any = ...,
        label: str | None = ...,
        table_name: str | None = ...,
        readable: bool = ...,
        listable: bool = ...,
    ) -> None: ...
    def bind(self, table: Table, name: str) -> None: ...

class FieldMethod:
    name: str
    f: Callable[..., Any]
    handler: Any
    def __init__(
        self,
        name: str | Callable[..., Any],
        f: Callable[..., Any] | None = ...,
        handler: Any = ...,
    ) -> None: ...
    def bind(self, table: Table, name: str) -> None: ...

class Field(Expression, Serializable):
    """A single column. Also the building block of queries: `db.t.f == 1`."""

    Virtual: type[FieldVirtual]
    Method: type[FieldMethod]
    Lazy: type[FieldMethod]

    name: str
    type: Any
    length: int | None
    default: Any
    required: bool
    requires: Any
    ondelete: str
    onupdate: str
    notnull: bool
    unique: bool
    uploadfield: bool | str
    widget: Any
    label: Any
    comment: Any
    writable: bool
    readable: bool
    searchable: bool
    listable: bool
    regex: str | None
    options: Any
    update: Any
    authorize: Any
    autodelete: bool
    represent: Any
    uploadfolder: str | None
    uploadseparate: bool
    uploadfs: Any
    compute: Callable[[Row], Any] | None
    map_none: Any
    # Unbound fields carry None here; `Field.clone()` resets them too.
    db: DAL | None
    table: Table | None
    _table: Table | None
    _db: DAL | None
    _rname: str
    _raw_rname: str
    _tablename: str
    _itype: str | None
    type_name: str
    isattachment: bool
    custom_store: Any
    custom_retrieve: Any
    custom_retrieve_file_properties: Any
    custom_delete: Any
    custom_qualifier: Any
    filter_in: Callable[[Any], Any] | None
    filter_out: Callable[[Any], Any] | None

    def __init__(
        self,
        fieldname: str,
        type: _Types = ...,
        length: int | None = ...,
        default: Any = ...,
        required: bool = ...,
        requires: Any = ...,
        ondelete: str = ...,
        onupdate: str = ...,
        notnull: bool = ...,
        unique: bool = ...,
        uploadfield: bool | str = ...,
        widget: Any = ...,
        label: Any = ...,
        comment: Any = ...,
        writable: bool = ...,
        readable: bool = ...,
        searchable: bool = ...,
        listable: bool = ...,
        regex: str | None = ...,
        options: Any = ...,
        update: Any = ...,
        authorize: Any = ...,
        autodelete: bool = ...,
        represent: Any = ...,
        uploadfolder: str | None = ...,
        uploadseparate: bool = ...,
        uploadfs: Any = ...,
        compute: Callable[[Row], Any] | None = ...,
        custom_store: Any = ...,
        custom_retrieve: Any = ...,
        custom_retrieve_file_properties: Any = ...,
        custom_delete: Any = ...,
        filter_in: Callable[[Any], Any] | None = ...,
        filter_out: Callable[[Any], Any] | None = ...,
        custom_qualifier: Any = ...,
        map_none: Any = ...,
        rname: str | None = ...,
        **others: Any,
    ) -> None: ...
    def set_attributes(self, **attributes: Any) -> Field: ...
    def clone(self, point_self_references_to: Any = ..., **args: Any) -> Field: ...
    def validate(self, value: Any, record_id: Any = ...) -> tuple[Any, Any]: ...
    def count(self, distinct: bool | None = ...) -> Expression: ...
    def as_dict(self, flat: bool = ..., sanitize: bool = ...) -> dict[str, Any]: ...
    def store(self, file: Any, filename: str | None = ..., path: str | None = ...) -> str: ...
    def retrieve(self, name: str, path: str | None = ..., nameonly: bool = ...) -> Any: ...
    def retrieve_file_properties(self, name: str, path: str | None = ...) -> dict[str, Any]: ...
    def formatter(self, value: Any, none_value: Any = ...) -> Any: ...
    def bind(self, table: Table) -> None: ...
    def has_default_validator(self) -> bool: ...
    def referenced_field(self) -> Field | None: ...
    def referenced_table(self) -> Table | None: ...
    @staticmethod
    def _todate(value: Any, regex: Any = ...) -> Any: ...
    @staticmethod
    def _todatetime(value: Any, regex: Any = ...) -> Any: ...
    @staticmethod
    def _totime(value: Any, regex: Any = ...) -> Any: ...
    def __hash__(self) -> int: ...
    @property
    def sqlsafe(self) -> str: ...
    @property
    def sqlsafe_name(self) -> str: ...
    @property
    def longname(self) -> str: ...

class Query(Serializable):
    """A boolean SQL condition. Combine with `&`, `|` and `~`."""

    db: DAL
    _db: DAL
    op: Any
    first: Any
    second: Any
    ignore_common_filters: bool
    optional_args: dict[str, Any]

    @property
    def _dialect(self) -> Any: ...
    def __init__(
        self,
        db: DAL,
        op: Any,
        first: Any = ...,
        second: Any = ...,
        ignore_common_filters: bool = ...,
        **optional_args: Any,
    ) -> None: ...
    def __and__(self, other: Query | Expression | bool) -> Query: ...
    def __rand__(self, other: Query | Expression | bool) -> Query: ...
    def __or__(self, other: Query | Expression | bool) -> Query: ...
    def __ror__(self, other: Query | Expression | bool) -> Query: ...
    def __invert__(self) -> Query: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def case(self, t: Any = ..., f: Any = ...) -> Expression: ...
    def as_dict(self, flat: bool = ..., sanitize: bool = ...) -> dict[str, Any]: ...

class Set(Serializable):
    """The rows matched by a query; the object returned by `db(query)`."""

    db: DAL
    _db: DAL
    query: Query | None
    dquery: Any

    def __init__(
        self, db: DAL, query: Query | None, ignore_common_filters: bool | None = ...
    ) -> None: ...
    def __call__(self, query: Query, ignore_common_filters: bool = ...) -> Set: ...
    def where(self, query: Query, ignore_common_filters: bool = ...) -> Set: ...
    def isempty(self) -> bool: ...
    def count(self, distinct: Any = ..., cache: Any = ...) -> int: ...
    def select(self, *fields: Any, **attributes: Any) -> Rows: ...
    def iterselect(self, *fields: Any, **attributes: Any) -> IterRows: ...
    def nested_select(self, *fields: Any, **attributes: Any) -> Select: ...
    def cte(self, name: str, *fields: Any, **attributes: Any) -> Select: ...
    def delete(self) -> int: ...
    def delete_naive(self) -> int: ...
    def update(self, **update_fields: Any) -> int: ...
    def update_naive(self, **update_fields: Any) -> int: ...
    def validate_and_update(self, **update_fields: Any) -> dict[str, Any]: ...
    def parse(self, dquery: Mapping[str, Any]) -> Query: ...
    def build(self, d: Mapping[str, Any]) -> Query: ...
    def as_dict(self, flat: bool = ..., sanitize: bool = ...) -> dict[str, Any]: ...
    def _count(self, distinct: Any = ...) -> str: ...
    def _select(self, *fields: Any, **attributes: Any) -> str: ...
    def _delete(self) -> str: ...
    def _update(self, **update_fields: Any) -> str: ...
    def _build_update_row(self, update_fields: Mapping[str, Any]) -> OpRow: ...
    def _apply_update(self, table: Table, row: OpRow, run_callbacks: bool) -> int: ...

class LazyReferenceGetter:
    db: DAL
    tablename: str
    id: Any
    def __init__(self, table: Table, id: Any) -> None: ...
    def __call__(self, other_tablename: str) -> LazySet: ...
    def __getattr__(self, key: str) -> LazySet: ...

class LazySet:
    field: Field
    id: Any
    def __init__(self, field: Field, id: Any) -> None: ...
    def _getset(self) -> Set: ...
    def __call__(self, query: Query, ignore_common_filters: bool = ...) -> Set: ...
    def where(self, query: Query, ignore_common_filters: bool = ...) -> Set: ...
    def isempty(self) -> bool: ...
    def count(self, distinct: Any = ..., cache: Any = ...) -> int: ...
    def select(self, *fields: Any, **attributes: Any) -> Rows: ...
    def nested_select(self, *fields: Any, **attributes: Any) -> Select: ...
    def delete(self) -> int: ...
    def delete_naive(self) -> int: ...
    def update(self, **update_fields: Any) -> int: ...
    def update_naive(self, **update_fields: Any) -> int: ...
    def validate_and_update(self, **update_fields: Any) -> dict[str, Any]: ...
    def _count(self, distinct: Any = ...) -> str: ...
    def _select(self, *fields: Any, **attributes: Any) -> str: ...
    def _delete(self) -> str: ...
    def _update(self, **update_fields: Any) -> str: ...

class VirtualCommand:
    method: Callable[..., Any]
    row: Row
    def __init__(self, method: Callable[..., Any], row: Row) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class BasicRows:
    db: DAL
    colnames: list[str]
    fields: Any
    compact: bool
    response: Any

    def __bool__(self) -> bool: ...
    def as_trees(
        self, parent_name: str = ..., children_name: str = ..., render: bool = ...
    ) -> list[Row]: ...
    def as_list(
        self,
        compact: bool = ...,
        storage_to_dict: bool = ...,
        datetime_to_str: bool = ...,
        custom_types: Any = ...,
    ) -> list[Any]: ...
    def as_dict(
        self,
        key: str = ...,
        compact: bool = ...,
        storage_to_dict: bool = ...,
        datetime_to_str: bool = ...,
        custom_types: Any = ...,
    ) -> dict[Any, Any]: ...
    def xml(self, strict: bool = ..., row_name: str = ..., rows_name: str = ...) -> str: ...
    def as_xml(self, row_name: str = ..., rows_name: str = ...) -> str: ...
    def as_json(self, mode: str = ..., default: Callable[[Any], Any] | None = ...) -> str: ...
    def json(self, mode: str = ..., default: Callable[[Any], Any] | None = ...) -> str: ...
    def as_csv(self) -> str: ...
    def colnames_fields(self) -> list[Any]: ...
    def export_to_csv_file(self, ofile: Any, null: str = ..., *args: Any, **kwargs: Any) -> None: ...

class Rows(BasicRows):
    """The result of `Set.select()`: a sequence of `Row`s."""

    records: list[Row]

    def __init__(
        self,
        db: DAL | None = ...,
        records: Any = ...,
        colnames: Sequence[str] = ...,
        compact: bool = ...,
        rawrows: Any = ...,
        fields: Sequence[Any] = ...,
    ) -> None: ...
    def setvirtualfields(self, **keyed_virtualfields: Any) -> Rows: ...
    def __add__(self, other: Rows) -> Rows: ...
    def __and__(self, other: Rows) -> Rows: ...
    def __or__(self, other: Rows) -> Rows: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, i: int) -> Row: ...
    @overload
    def __getitem__(self, i: slice) -> list[Row]: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __eq__(self, other: object) -> bool: ...
    def column(self, column: Any = ...) -> list[Any]: ...
    def first(self) -> Row | None: ...
    def last(self) -> Row | None: ...
    def append(self, row: Row) -> None: ...
    def insert(self, position: int, row: Row) -> None: ...
    def find(self, f: Callable[[Row], Any], limitby: _Limitby | None = ...) -> Rows: ...
    def exclude(self, f: Callable[[Row], Any]) -> Rows: ...
    def sort(self, f: Callable[[Row], Any], reverse: bool = ...) -> Rows: ...
    def join(
        self,
        field: Field,
        name: str | None = ...,
        constraint: Query | None = ...,
        fields: Sequence[Any] = ...,
        orderby: _Orderby = ...,
    ) -> Rows: ...
    def group_by_value(self, *fields: Any, **args: Any) -> dict[Any, Any]: ...
    def render(self, i: int | None = ..., fields: Sequence[Any] | None = ...) -> Any: ...
    def _restore_fields(self, fields: Any) -> Rows: ...

class IterRows(BasicRows):
    """Streaming variant of `Rows` returned by `Set.iterselect()`."""

    sql: str
    blob_decode: bool
    cacheable: bool
    cursor: Any
    last_item: Row | None
    last_item_id: Any
    _head: Row | None

    def __init__(
        self,
        db: DAL,
        sql: str,
        fields: Sequence[Any],
        colnames: Sequence[str],
        blob_decode: bool = ...,
        cacheable: bool = ...,
    ) -> None: ...
    def __iter__(self) -> IterRows: ...
    def __next__(self) -> Row: ...
    def next(self) -> Row: ...
    def __getitem__(self, key: int) -> Row: ...
    def first(self) -> Row | None: ...

def csv_reader(
    utf8_data: Any, dialect: Any = ..., encoding: str = ..., **kwargs: Any
) -> Iterator[list[str]]: ...
def get_default_validator(db: DAL, field: Field) -> Any: ...
