from typing import Any, Callable, Generic, Iterable, Iterator, Mapping, TypeVar, overload

from ..objects import Field, Row, Table

_T = TypeVar("_T")
_C = TypeVar("_C")

class cachedprop(Generic[_T]):
    def __init__(self, fget: Callable[[Any], _T], doc: str | None = ...) -> None: ...
    @overload
    def __get__(self, obj: None, objtype: type[Any] | None = ...) -> cachedprop[_T]: ...
    @overload
    def __get__(self, obj: Any, objtype: type[Any] | None = ...) -> _T: ...

class BasicStorage:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def has_key(self, key: str) -> bool: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def keys(self) -> Iterable[str]: ...
    def iterkeys(self) -> Iterator[str]: ...
    def values(self) -> Iterable[Any]: ...
    def itervalues(self) -> Iterator[Any]: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def iteritems(self) -> Iterator[tuple[str, Any]]: ...
    def pop(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self) -> None: ...
    def copy(self) -> dict[str, Any]: ...

def pickle_basicstorage(s: BasicStorage) -> tuple[Any, ...]: ...

class OpRow:
    """Mutable field/value pair collector handed to insert and update callbacks."""

    def __init__(self, table: Table) -> None: ...
    def set_value(self, key: str, value: Any, field: Field | None = ...) -> None: ...
    def del_value(self, key: str) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __getattr__(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __delattr__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def keys(self) -> Iterable[str]: ...
    def iterkeys(self) -> Iterator[str]: ...
    def values(self) -> Iterable[Any]: ...
    def itervalues(self) -> Iterator[Any]: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def iteritems(self) -> Iterator[tuple[str, Any]]: ...
    def op_values(self) -> list[tuple[Field, Any]]: ...

class Serializable:
    def as_dict(self, flat: bool = ..., sanitize: bool = ...) -> dict[str, Any]: ...
    def as_xml(self, sanitize: bool = ...) -> str: ...
    def as_json(self, sanitize: bool = ...) -> str: ...
    def as_yaml(self, sanitize: bool = ...) -> str: ...

class Reference(int):
    """An `int` primary key that lazily loads the referenced record on attribute access."""

    _table: Table
    _record: Row | None
    def __getattr__(self, key: str, default: Any = ...) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...

def Reference_unpickler(data: bytes) -> Any: ...
def Reference_pickler(data: Reference) -> tuple[Any, ...]: ...

class SQLCallableList(list[str]):
    def __call__(self) -> SQLCallableList: ...

class SQLALL:
    """`table.ALL`: expands to every field of `_table` in a select."""

    _table: Table
    def __init__(self, table: Table) -> None: ...

class SQLCustomType:
    type: str
    native: str | None
    encoder: Callable[[Any], Any]
    decoder: Callable[[Any], Any]
    validator: Any
    widget: Any
    represent: Any
    def __init__(
        self,
        type: str = ...,
        native: str | None = ...,
        encoder: Callable[[Any], Any] | None = ...,
        decoder: Callable[[Any], Any] | None = ...,
        validator: Any = ...,
        _class: str | None = ...,
        widget: Any = ...,
        represent: Any = ...,
    ) -> None: ...
    def startswith(self, text: str | None = ...) -> bool: ...
    def endswith(self, text: str | None = ...) -> bool: ...
    def __getitem__(self, i: Any) -> None: ...

class RecordOperator:
    colset: Any
    db: Any
    tablename: str
    id: Any
    def __init__(self, colset: Any, table: Table, id: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class RecordUpdater(RecordOperator): ...
class RecordDeleter(RecordOperator): ...

class MethodAdder:
    table: Table
    def __init__(self, table: Table) -> None: ...
    def __call__(self) -> Callable[[_C], _C]: ...
    def __getattr__(self, method_name: str) -> Callable[[_C], _C]: ...
    def register(self, method_name: str | None = ...) -> Callable[[_C], _C]: ...

class FakeCursor:
    def warn_bad_usage(self, attr: str) -> None: ...
    def __getattr__(self, attr: str) -> Any: ...
    def __setattr__(self, attr: str, value: Any) -> None: ...

class NullCursor(FakeCursor): ...

class FakeDriver(BasicStorage):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def cursor(self) -> FakeCursor: ...

class NullDriver(FakeDriver): ...

class ExecutionHandler:
    """Hook invoked around every statement the adapter executes."""

    adapter: Any
    def __init__(self, adapter: Any) -> None: ...
    def before_execute(self, command: str) -> None: ...
    def after_execute(self, command: str) -> None: ...

class TimingHandler(ExecutionHandler):
    MAXSTORAGE: int
    @property
    def timings(self) -> list[tuple[str, float]]: ...

class DatabaseStoredFile:
    web2py_filesystems: set[str]
    db: Any
    filename: str
    def __init__(self, db: Any, filename: str, mode: str) -> None: ...
    def escape(self, obj: Any) -> Any: ...
    @staticmethod
    def try_create_web2py_filesystem(db: Any) -> None: ...
    def read(self, bytes: int | None = ...) -> Any: ...
    def readinto(self, bytes: Any) -> Any: ...
    def readline(self) -> Any: ...
    def write(self, data: Any) -> None: ...
    def close_connection(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def is_operational_error(db: Any, error: BaseException) -> bool: ...
    @staticmethod
    def is_programming_error(db: Any, error: BaseException) -> bool: ...
    @staticmethod
    def exists(db: Any, filename: str) -> bool: ...
